#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${AIRFLOW_USER} WITH PASSWORD '${AIRFLOW_PASSWORD}';
    CREATE DATABASE ${AIRFLOW_DB} OWNER ${AIRFLOW_USER};
    REVOKE CONNECT ON DATABASE ${AIRFLOW_DB} FROM PUBLIC;
    REVOKE CONNECT ON DATABASE ${POSTGRES_DB} FROM PUBLIC;
EOSQL